name: deferred_state
description: Provides a simple method of doing async initialisation in a StatefulWidget
version: 1.1.0
repository: https://github.com/onepub-dev/deferred_state

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  future_builder_ex: ^5.0.0

dev_dependencies:
  lint_hard: ^5.0.0
  test: ^1.24.0
